// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCVProfile(arg1) {
  return window['go']['main']['App']['CreateCVProfile'](arg1);
}

export function FetchCVAndSave(arg1, arg2) {
  return window['go']['main']['App']['FetchCVAndSave'](arg1, arg2);
}

export function FetchDigitalSkillsAutocomplete(arg1) {
  return window['go']['main']['App']['FetchDigitalSkillsAutocomplete'](arg1);
}

export function GetPdfFile(arg1) {
  return window['go']['main']['App']['GetPdfFile'](arg1);
}

export function OpenPDF(arg1) {
  return window['go']['main']['App']['OpenPDF'](arg1);
}

export function Translate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Translate'](arg1, arg2, arg3);
}

export function TranslateHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranslateHTML'](arg1, arg2, arg3);
}

export function UpdateCVProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateCVProfile'](arg1, arg2);
}
