// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCVProfile(arg1) {
  return window['go']['main']['App']['CreateCVProfile'](arg1);
}

export function CreateOrUpdateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateOrUpdateProfile'](arg1, arg2, arg3, arg4);
}

export function CreateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function FetchCVAndSave(arg1, arg2) {
  return window['go']['main']['App']['FetchCVAndSave'](arg1, arg2);
}

export function FetchDigitalSkillsAutocomplete(arg1) {
  return window['go']['main']['App']['FetchDigitalSkillsAutocomplete'](arg1);
}

export function GetPdfFile(arg1) {
  return window['go']['main']['App']['GetPdfFile'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfilesOfUser(arg1) {
  return window['go']['main']['App']['GetProfilesOfUser'](arg1);
}

export function GetUserByID(arg1) {
  return window['go']['main']['App']['GetUserByID'](arg1);
}

export function GetUsersPaginated(arg1, arg2) {
  return window['go']['main']['App']['GetUsersPaginated'](arg1, arg2);
}

export function OpenPDF(arg1) {
  return window['go']['main']['App']['OpenPDF'](arg1);
}

export function SearchUsers(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchUsers'](arg1, arg2, arg3);
}

export function Translate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Translate'](arg1, arg2, arg3);
}

export function TranslateHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranslateHTML'](arg1, arg2, arg3);
}

export function UpdateCVProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateCVProfile'](arg1, arg2);
}

export function UpdateProfileID(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfileID'](arg1, arg2, arg3);
}

export function UpdateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3, arg4);
}
