// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchCV(arg1:string):Promise<Array<number>>;

export function Translate(arg1:string,arg2:string,arg3:string):Promise<string>;
