// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCVProfile(arg1:string):Promise<string>;

export function FetchCVAndSave(arg1:string):Promise<string>;

export function FetchDigitalSkillsAutocomplete(arg1:string):Promise<Array<string>>;

export function GetPdfFile(arg1:string):Promise<Array<number>>;

export function OpenPDF(arg1:string):Promise<void>;

export function Translate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TranslateHTML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateCVProfile(arg1:string,arg2:string):Promise<string>;
