name: Compile and Release Wails Application

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.21"

      - name: Clone Wails Repository with Depth 1
        run: git clone --depth 1 https://github.com/wailsapp/wails.git

      - name: Install Wails Dependencies
        run: cd wails && go get -v -t

      - name: Build Wails Binary
        run: cd wails && go build -o wails./cmd/wails

      - name: Build Wails Application
        run: ./wails build -webview2 embed -platform "windows/amd64" -nsis -upx -debug

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: cv-amd64-installer.exe
          asset_path: "./build/bin/"
          asset_content_type: application/octet-stream
